### ISSUE TITLE
Input file content is not displayed.

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#19]
## Problem description

When opening any custom input file, clicking on "Show input" will only display `[object ProgressEvent]` instead of the actual file content.

## Expected behaviour

The actual file content should be shown.

## Screenshot

See (A) in the screenshot for an example.

![screenshot_forna_1](https://user-images.githubusercontent.com/1579775/70132070-bae02500-1683-11ea-9088-1f16c5b38baa.png)

**Comment by bad-ants-fleet** [comment]
should be fixed now
