### ISSUE TITLE
Improve time axis labelling.

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#20]
## Problem description

The plotting of labels on the time axis has multiple issues. The labels may overlap. Sometimes the axis ticks are labelled, sometimes they aren't. Sometimes, there are no labels or ticks at all on big parts of the axis.

## Expected behavior

The labels should be evenly distributed and clearly visible. They should not overlap.

## Screenshot

See (B) in the screenshot for an example of overlapping labels, and (F) for an example of missing / too few labels. Output (B) is computed with the attached input file `forna.txt`, output (F) is the built-in "small example".

![screenshot_forna_1](https://user-images.githubusercontent.com/1579775/70132496-a7818980-1684-11ea-9bbf-4df64aeea7ff.png)
![screenshot_forna_3](https://user-images.githubusercontent.com/1579775/70132530-b9632c80-1684-11ea-9452-e7bf08d1b4fd.png)

[forna.txt](https://github.com/ViennaRNA/drforna/files/3921189/forna.txt)

**Comment by bad-ants-fleet** [comment]
fixed in the latest version
