### ISSUE TITLE
Coloring of the structure plot is sometimes broken.

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#22]
## Problem description

Sometimes the coloring shown in the secondary structure (dot--bracket) list at the bottom is not correctly applied to the drawing. In the example below, for structure 1, only the lines connecting the base pairs are colored (and not the nodes themselves), and for structure 7, only some nodes are colored. Also, only red color is used in the plots.

## Expected behaviour

The structure plots should be colored as visualized in the dot--bracket structure list, i.e. with the respective color and at the respective positions. 

## Screenshot

See (C) in the screenshot for an example. It was generated using 
[forna.txt](https://github.com/ViennaRNA/drforna/files/3921346/forna.txt) as input.

![screenshot_forna_2](https://user-images.githubusercontent.com/1579775/70135255-fa117480-1689-11ea-95e4-5ef9113bfe15.png)

**Comment by bad-ants-fleet** [comment]
This is expected behaviour. The first occurence of an ID determines the colors in the scale area.
