### ISSUE TITLE
Display more information.

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#23]
This is a feature request. Please show some more, useful information in the output:

1) Show the input sequence above the structures *in the dot--bracket list*. 

    Also add sequences to the examples such that the user knows how to format the input properly.
2) Show the exact time value of the cursor. This makes it much easier to navigate especially on a log-scale time axis.

**Comment by bad-ants-fleet** [comment]
should all be taken care of in the latest version
