### ISSUE TITLE
Running IDs break DrForna 

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#24]
## Problem description

When using a running ID (i.e. numbers 1, 2, 3, ...) for all input structures across all time steps, no structure is displayed in the output at all.

## Expected behaviour

The structures should be printed anyway, I guess. The dot--bracket strings should be listed below.

## Screenshot

Using [forna.out.runidx.txt](https://github.com/ViennaRNA/drforna/files/3921420/forna.out.runidx.txt) generates the following blank output:

![screenshot_forna_4](https://user-images.githubusercontent.com/1579775/70136774-f0d5d700-168c-11ea-85fc-92d7fa33ad24.png)

**Comment by bad-ants-fleet** [comment]
fixed in latest version
