### ISSUE TITLE
Visual glitch: Structure list vs. page scrolling 

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#26]
## Problem description

When the "Show Input" field is extended, the dot--bracket structure list is close to the screen bottom. When there are a lot of structures, one has to scroll down. When moving the cursor and the structure list becomes shorter again (i.e. fewer structures are displayed), the page becomes shorter. Now, when moving the cursor back to the original position , one has to scroll down again to see the same structures. This is quite annoying.

## Example 

Take the built-in "short example". Click "Show Input" such that the header of the structure list is displayed at the bottom of the screen. Move the cursor over the entire time axis, forth and back.  One has to scroll repeatedly to keep all structures on the screen.

## Suggested fix

Allow scrolling past the end of the website / structure list (a setting known from text editors), or give the structure list a minimal height.

**Comment by bad-ants-fleet** [comment]
We now provide the summary table in a new window, I think this should fix this issue.
