### ISSUE TITLE
The tRNA example causes a severe memory leak

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#27]
## Problem description

Selecting the tRNA example causes the browser to go rogue and eat up all memory, while only the text "Loading ..." is displayed. Only killing the browser process prevents the system from freezing.

## Technical information

This happens on a Fedora 30 Workstation with Firefox 70.0.1 x64 as well as Chrome 78.0.3904.108 x64.

**Comment by bad-ants-fleet** [comment]
should be fixed in latest version
