### ISSUE TITLE
Inconsistencies in displayed data

### ISSUE THREAD

**Issue by xileF1337** [pkerpedjiev/drforna#28]
## Problem description

Sometimes the information showed is inconsistent with the input, i.e. structures are displayed at a different time and with a different occupancy than they have in the input.

## Example

This only seems to happen with my own generated input. May this be related to the IDs I used? The input is [forna.txt](https://github.com/ViennaRNA/drforna/files/3921921/forna.txt).

Here, structure 1 has an energy of -24.8 (cf. (D)) -- it is the only structure with this energy value in the input. However, it has an occupancy of 9.04e-02 = 0.09 in the input instead of the 0.78 displayed by DrForna, cf. (D). Also, the occupancy values do not sum up to 1. Additionally, the time labels are somewhat off, the structure is displayed before time 4e4 in DrForna (cf. (E), but has time 4.3e4 in the input file.

![screenshot_forna_2](https://user-images.githubusercontent.com/1579775/70145240-ec66e980-169f-11ea-9c06-72e38eab07ba.png)

**Comment by bad-ants-fleet** [comment]
should be fixed in latest master branch.
