### ISSUE TITLE
better navigation on the time axis

### ISSUE THREAD

**Issue by j-4** [pkerpedjiev/drforna#6]
- Need a way to freeze the current view on the time axis
  mayby clicking on the timeaxis freezes the view there, clicking again makes it change with hover again? would be nice and intuitive i guess!
- Navigation with arrow keys would be really helpful as soon as the navigaion is "frozen" on a current timepoint!

**Comment by svenderheld** [comment]
The arrow key navigation would be not only useful if the view is "frozen". It would be need to exactly navigate between transcription steps.

**Comment by j-4** [comment]
clicking on the timeline now freezes the current position.
Moreover, there is a `container.toggleAnimation(delay=100, fromStart=false)` function which allows you to start an automated animation with the given parameters. If `delay` is set to zero, the animation will jump only one "frame" which allows you to jump forward with e.g., keyboard bindings on you application
