### ISSUE TITLE
Option whether time should be a log scale

### ISSUE THREAD

**Issue by pkerpedjiev** [pkerpedjiev/drforna#9]
The scale should switch to log values after the end of transcription to show a wider variety of output structures.

[random01.zip](https://github.com/pkerpedjiev/drforna/files/1036633/random01.zip)
[random01.pdf](https://github.com/pkerpedjiev/drforna/files/1036634/random01.pdf)

**Comment by j-4** [comment]
I would like to have an option to switch on/off the log scale.

**Comment by bad-ants-fleet** [comment]
fixed
